### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lodekib** [JibayMcs/filament-tour#1]
### What happened?

I get this error **Target class [hash] does not exist.** when i try to use a closure that returns boolean inside the method onlyVisibleOnce().

### How to reproduce the bug

->onlyVisibleOnce(fn() : bool => Auth::user()->is_verified)

### Package Version

3.x-dev

### PHP Version

8.2

### Laravel Version

10

**Comment by JibayMcs** [comment]
After some research, it seems that the user cannot be instantiated in the "AdminPanelProvider" context.

I tested with :

Auth::user()
auth()->user()
Filament::auth()->user()

Do not use an authentication check at this stage. **¯\\_(ツ)_/¯**

I know it sounds redundant, but using `Tour::make('my_tour')->visible(auth()->user()->is_verified)` seems the best solution at the moment.
