### ISSUE TITLE
Can’t open tour from getHeaderActions but does work from widget button.

### ISSUE THREAD

**Issue by RicLeP** [JibayMcs/filament-tour#12]
### What happened?

Launching a tour from a page header action does not work, I have the following:

```
 protected function getHeaderActions(): array
    {
        return [
            Action::make('Tour')->dispatch('filament-tour::open-tour', ['tour_dashboard']),
        ];
    }
```
When clicking the button I get this error `Tour with id 'tour_dashboard' not found`.

However, if I add this to a widget’s view on the same page, it will launch the tour as expected.

```
<button wire:click="$dispatch('filament-tour::open-tour', 'tour_dashboard')">Tour</button>
```

### How to reproduce the bug

Create a tour on a custom dashboard then include a header action to dispatch the open-tour event.

### Package Version

3.1.0.3

### PHP Version

8.2.15

### Laravel Version

10.46.0

### Which operating systems does with happen with?

Windows

**Comment by invaders-xx** [comment]
I have the same issue : console displays "Tour with id 'blabla'  not found

**Comment by FDT2k** [comment]
Same for me.

**Comment by FDT2k** [comment]
Solution here #8   Adding tour_  before the id  

```php 
Action::make('demo')->link()->action(fn($livewire)=>$livewire->dispatch('filament-tour::open-tour', 'tour_YOUR_ID')),

// or 

Action::make('demo')->link()->dispatch('filament-tour::open-tour', ['tour_YOUR_ID']),

```

**Comment by JibayMcs** [comment]
Hi ! This bug will be fixed in the next release !

**Comment by JibayMcs** [comment]
Fixed here: https://github.com/JibayMcs/filament-tour/releases/tag/v3.1.0.6
