### ISSUE TITLE
[Bug]:  Missing required parameter for [Route: xxx.edit] [URI: app/xxx/{record}/edit] [Missing parameter: record].

### ISSUE THREAD

**Issue by wallacemaxters** [JibayMcs/filament-tour#25]
### What happened?

> Missing required parameter for [Route: filament.admin.resources.simulacoes.edit] [URI: app/simulacoes/{record}/edit] [Missing parameter: record].

It's caused because the line https://github.com/JibayMcs/filament-tour/blob/v3.1.0.9/src/Tour/HasTour.php#L22 changed with `Filament::auth()->user()` .  

In this cases, I have changed the name of route using the `route`  method, but with the additional check added in the above code causes the error, because it not consider my manual change.

### How to reproduce the bug

For reproducion, install the version 3.1.0.6 or greather and add tour trait in page that uses {record} parameter (view or edit record page).

### Package Version

3.1.0.6 >=

### PHP Version

8.2.0

### Laravel Version

10.0

**Comment by OccTherapist** [comment]
I believe this is the same bug as my #23. So maybe try my promoted fix #24

**Comment by JonathanVorich** [comment]
@OccTherapist I dont think so. I get the same error, even why I add you fix manually, when i am authenticated and navigate to the route with {record}

@wallacemaxters any fix or workaround found?

**Comment by JonathanVorich** [comment]
I think its related to https://github.com/JibayMcs/filament-tour/issues/20

**Comment by JonathanVorich** [comment]
I use a workaround till this bug gets fixed. you need to adjust the explode key for your route 😉 

```
public function tours(): array
    {
        //can be removed after PR is merged: https://github.com/JibayMcs/filament-tour/pull/24
        if (! Filament::auth()->user()) {
            return [];
        }

        return [
            Tour::make('example_create')
                ->steps(
                    Step::make()
                        ->title('Example title')
                        ->description('Example description, lorem ipsum ...'),
                )
                //can be removed after bug is fixed https://github.com/JibayMcs/filament-tour/issues/20 or https://github.com/JibayMcs/filament-tour/issues/25 (same)
                ->route('/app/examples/'.explode('/', parse_url(url()->previous())['path'])[3].'/edit'),
        ];
    }
```

**Comment by JibayMcs** [comment]
Now fixed with the work on @OccTherapist ! <3 
https://github.com/JibayMcs/filament-tour/releases/tag/v3.1.1
