### ISSUE TITLE
[How To]: Tour/Highlight on ul > li elements (Sidebar)

### ISSUE THREAD

**Issue by lodekib** [JibayMcs/filament-tour#3]
### What happened?

Not really a bug,I would really want to show the tour on each of the sidebars' navigation item.They all have the class ```.fi-sidebar-item``` , how do i access each of  this elements in the ```Step::make()``` method? E.g suppose i have three nav items ```posts``` , ```category``` , ```sales``` . If i want to show a tour for all of them one after the other alongside there relevant description, how do i select each element ?

### How to reproduce the bug

Try to select the nav items from their  ```Step::make()``` method. 

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by JibayMcs** [comment]
According you always have the "Dashboard" Sidebar item.

The following code gonna work:

```php
Step::make('li.fi-sidebar-item:nth-of-type(2)')->title('Posts'),

Step::make('li.fi-sidebar-item:nth-of-type(3)')->title('Categories'),

Step::make('li.fi-sidebar-item:nth-of-type(4)')->title('Sales')
```

**Comment by lodekib** [comment]
Thank you .It works. Suppose the sidebar items are inside navigation 
groups?
